name: math-art

dependencies:
  - base == 4.*
  - tasty
  - unordered-containers
  - matrix
  - prizm >=3.0 && <4.0
  - gloss
  - NumInstances >=1.4 && <1.5
  - vector-space >=0.10
  - vector >=0.11
  - diagrams-svg >=1.3
  - diagrams-lib >=1.3
  - palette >=0.1 && <0.2
  - StateVar >=1.1 && <1.2
  - GLUT >=2.7 && <2.8
  - convertible
  - mwc-random

executables:
  octaplex:
    source-dirs: octaplex
    main: Main.hs
    dependencies:
      - math-art
  sphere:
    source-dirs: sphere
    main: Main.hs
    dependencies:
      - math-art
  color_polyhedron:
    source-dirs: color_polyhedron
    main: Main.hs
    dependencies:
      - math-art
  disk:
    source-dirs: disk
    main: Main.hs
    dependencies:
      - math-art
  triangles:
    source-dirs: triangles
    main: Main.hs
    dependencies:
      - math-art

library:
  source-dirs: lib
  exposed-modules:
    - Geometry
    - ColorSpace

# tests:
#   tests:
#     main: Tests.hs
#     source-dirs:
#       - tests
#     dependencies:
#       - HUnit
#       - tasty
#       - tasty-hunit
#       - hive

ghc-options:
  - -O2
  - -threaded
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns
